"""add vessels table

Revision ID: 3037a8e8862b
Revises: 
Create Date: 2026-03-23 02:19:50.447451

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3037a8e8862b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vessels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mmsi', sa.String(length=9), nullable=False),
    sa.Column('imo', sa.String(length=10), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('call_sign', sa.String(length=10), nullable=True),
    sa.Column('flag', sa.String(length=3), nullable=True),
    sa.Column('vessel_type', sa.Enum('cargo', 'tanker', 'passenger', 'fishing', 'tug', 'military', 'pleasure', 'other', 'unknown', name='vesseltype'), nullable=False),
    sa.Column('length', sa.Float(), nullable=True),
    sa.Column('beam', sa.Float(), nullable=True),
    sa.Column('draught', sa.Float(), nullable=True),
    sa.Column('gross_tonnage', sa.Float(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('speed_over_ground', sa.Float(), nullable=True),
    sa.Column('course_over_ground', sa.Float(), nullable=True),
    sa.Column('heading', sa.Float(), nullable=True),
    sa.Column('nav_status', sa.Enum('under_way_engine', 'at_anchor', 'not_under_command', 'restricted_maneuverability', 'moored', 'aground', 'unknown', name='navigationstatus'), nullable=False),
    sa.Column('position_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('imo')
    )
    op.create_index(op.f('ix_vessels_mmsi'), 'vessels', ['mmsi'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vessels_mmsi'), table_name='vessels')
    op.drop_table('vessels')
    # ### end Alembic commands ###
