"""add anomalies table

Revision ID: 4eca6a74321d
Revises: 78be115698b4
Create Date: 2026-03-23 02:47:29.310927

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4eca6a74321d'
down_revision: Union[str, Sequence[str], None] = '78be115698b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anomalies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mmsi', sa.String(length=9), nullable=False),
    sa.Column('anomaly_type', sa.Enum('dark_vessel', 'loitering', name='anomalytype'), nullable=False),
    sa.Column('status', sa.Enum('active', 'resolved', name='anomalystatus'), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_anomalies_mmsi'), 'anomalies', ['mmsi'], unique=False)
    op.create_index('ix_anomalies_mmsi_type_status', 'anomalies', ['mmsi', 'anomaly_type', 'status'], unique=False)
    op.create_table('vessel_tracks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mmsi', sa.String(length=9), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('speed_over_ground', sa.Float(), nullable=True),
    sa.Column('course_over_ground', sa.Float(), nullable=True),
    sa.Column('heading', sa.Float(), nullable=True),
    sa.Column('nav_status', sa.Enum('under_way_engine', 'at_anchor', 'not_under_command', 'restricted_maneuverability', 'moored', 'aground', 'unknown', name='navigationstatus'), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mmsi', 'recorded_at', name='uq_vessel_tracks_mmsi_recorded_at')
    )
    op.create_index('ix_vessel_tracks_mmsi_recorded_at', 'vessel_tracks', ['mmsi', 'recorded_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_vessel_tracks_mmsi_recorded_at', table_name='vessel_tracks')
    op.drop_table('vessel_tracks')
    op.drop_index('ix_anomalies_mmsi_type_status', table_name='anomalies')
    op.drop_index(op.f('ix_anomalies_mmsi'), table_name='anomalies')
    op.drop_table('anomalies')
    # ### end Alembic commands ###
