"""add vessel_tracks table

Revision ID: 78be115698b4
Revises: 3037a8e8862b
Create Date: 2026-03-23 02:28:09.588688

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78be115698b4'
down_revision: Union[str, Sequence[str], None] = '3037a8e8862b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vessel_tracks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mmsi', sa.String(length=9), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('speed_over_ground', sa.Float(), nullable=True),
    sa.Column('course_over_ground', sa.Float(), nullable=True),
    sa.Column('heading', sa.Float(), nullable=True),
    sa.Column('nav_status', sa.Enum('under_way_engine', 'at_anchor', 'not_under_command', 'restricted_maneuverability', 'moored', 'aground', 'unknown', name='navigationstatus'), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mmsi', 'recorded_at', name='uq_vessel_tracks_mmsi_recorded_at')
    )
    op.create_index('ix_vessel_tracks_mmsi_recorded_at', 'vessel_tracks', ['mmsi', 'recorded_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_vessel_tracks_mmsi_recorded_at', table_name='vessel_tracks')
    op.drop_table('vessel_tracks')
    # ### end Alembic commands ###
